name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  manifest_secret: deployment-manifest
  approved_manifest: approved-release-manifest
  PARAM_MAP: |
        "approvers": "sanjit2appscrip"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" The type of runner that the job will run on

  get_name: 
    runs-on: ubuntu-latest
    steps:
      - name: print 
        run: |
          echo "sanjit swain"
          echo "sanjana panigrahi"

  logs-download:
    runs-on: ubuntu-latest
    needs: get_name
    outputs:
      job_id: ${{steps.job_id.outputs.job_id}}
    steps:   
         - name: job_id
           id: job_id
           run: |
              JOB_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                   -H "Accept: application/vnd.github+json" \
                   "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")           
              echo $JOB_ID
              job_id=$(echo "$JOB_ID" | jq '.jobs[] | select(.name == "get_name") | .id')
              echo $job_id
              echo "job_id=$job_id" >> $GITHUB_ENV
         - name: Download Workflow Logs
           run: |   
            curl -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -o workflow_logs.txt \
              https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/jobs/${{ env.job_id }}/logs
         - name: get logs
           run: |
              ls -all
              cat workflow_logs.txt
              
  rerun-job:
    runs-on: ubuntu-latest
    needs:  logs-download
    steps: 
       - name: Wait for 1 minute
         run: sleep 20
       - name: restart
         run: |
         
              echo "The job ID is ${{ needs.logs-download.outputs.job_id }}"
              curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/jobs/${{ needs.logs-download.outputs.job_id }}/rerun
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.0.0
  #     - name: Download 24hrs Old Logs
  #       uses: pawanbahuguna/action-logs/@v1.0.1
  #       env: 
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         GH_REPO: ${{ github.repository }}
  #     - uses: actions/checkout@v2.0.0
  #     - name: get Old Logs
  #       run: |
  #          ls
  #          ls -all 
