name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  manifest_secret: deployment-manifest
  approved_manifest: approved-release-manifest
  PARAM_MAP: |
        "approvers": "sanjit2appscrip"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" The type of runner that the job will run on

  get_name: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run a sample command
        id: run-sample
        run: |
          echo "Running a sample job..."
          echo "This is the sample job with name: ${{ github.job }}"
          
  get_workflow: 
       runs-on: ubuntu-latest
       steps:
          - name: Check out the repository
            uses: actions/checkout@v3
    
          - name: Run a sample command
            id: run-sample
            run: |
              echo "Running a sample job..."
              echo "This is the sample job with name: ${{ github.job }}"
  run_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Workflow Run ID
        id: get_run_id
        run: echo "RUN_ID=${{ github.run_id }}" > run_id.txt

      - name: Upload run ID
        uses: actions/upload-artifact@v3
        with:
          name: run-id
          path: run_id.txt
  
