# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest      
  get_approver_name:
    name: Get the Name of the Manifest Approver
    runs-on: ubuntu-latest
    environment:
      name: team-manifest-approver
    outputs:
      approver: ${{ steps.extract-approver.outputs.approver }}
      is_qadeployer: ${{ steps.check-approver.outputs.is_qadeployer }}
    steps:
      - name: echo github event details
        run: |
          echo ${{ github.event }}
          echo ${{ github.repository_owner }}
          echo ${{ github.event.repository.name }}
          echo ${{ github.run_id }}

      - name: Extract Approver Name
        id: extract-approver
        run: |
          payload=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{github.run_id}}/approvals )
          echo $payload
          approver=$(echo "$payload" | jq -r '.[].user.login')
          echo "approver=$approver" >>  $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      # - name: Get team members
      #   id: get-members
      - name: Check if Approver is in QADeployers Team
        id: check-approver
        run: |
          team_members=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/bayer-int )
          echo $team_members

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

