name: UPLOAD

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  logs-download:
         runs-on: ubuntu-latest
         steps: 
          - name: Download artifact
            id: download-artifact
            uses: dawidd6/action-download-artifact@v6
            with:
              workflow: blank.yml
              name: run-id
  
          - name: Read Run ID
            id: read_run_id
            run: |
              RUN_ID=$(cat run_id.txt)
              echo "RUN_ID=$RUN_ID"
              echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
              
          - name: Download Workflow Logs
            run: |
              curl -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ env.RUN_ID }}/logs -o workflow.zip
          - name: Upload workflowlogs
            uses: actions/upload-artifact@v3
            with:
              name: workflow-log
              path: workflow.zip
          - name: get logs
            run: |
              ls -all
              cat run_id.txt
